sudo: required
language: node_js
notifications:
  email: raphael@raphaellima.site
node_js:
- 5.12
services:
- postgresql
env:
  global:
  - NODE_ENV: test
  - TRAVIS: true
addons:
  postgresql: '9.3'
before_script:
- psql -c 'create database ts_api_test;' -U postgres
- npm i -g sequelize-cli gulp-cli
- cd server/
- sequelize db:migrate --env test
- npm install
- gulp
script:
- npm run unit-test
- npm run integration-test
deploy:
  provider: heroku
  api_key:
    secure: QOE4ipeqUyHU6ZwHi8QktJXDGirVqIlfHisNTL4nc91lF5Db9MW1QPb7RZ3Yq6oX73o4dZlyURGkAQ9yWuFylkumOLbmuYSJaiIxznoRrlbQTIlGRf+FTlqPsWhRek1xILA6SrziyCIhOmw/lGKEqD732ZXIfd7JOtjq04tlfrIQ71RgfpXuOiJgMEQJfGSA56Sl4vpFNrf+Uiay4ORRQGj9904Kx1px0xR8rF/BS8tONzjVJmrzdIfcHgybcG+1QOQi4eD7v4Wn25TlVKquffNVytMwuA2ozMKjZjA39DRPDHnebIKgdLn1Cywl3RDD3GB+04Hf8vBTgsFJy5TJ7YcijSKy4DGyHph2Q7rezlaxsfENLxiOeY28KV6uW1sxSj4mNbdJWJjpCjNwgkj9TPJBiUo7Nn/JP8ouHaKNvCyhPSy0vYzNnLvE1sN4Gkt3yiHXKt4RxTCZSNlBmBeVqs18Ao2fMZalJPWAvgdMOb0Bi1N3eATSJv08geK2fWIxm6sJSl+XJj/Z9cVn4+0gqeIVORclks0qfe3DvCYsGkBWKz0UL59wpt5hS9KhuH5gStNE2ppX8i/tRkAK2XnfODAi+mXksdKFJjtekB20xF0HXprBG7QaX8NTIchhYeXuU2mnm8TzbnWq0CBro6CB7PA5N72WkfRcpJhsF1EHL+c=
  app: typescript-course
  on:
    repo: raphaellima8/typescript-course
